Add implicit Ordering[RichDate]
see scala design issue: https://issues.scala-lang.org/browse/SI-8541
that causes the following for tuples with RichDate:

/Users/oscar/oss/scalding/scalding-date/src/test/scala/com/twitter/scalding/DateTest.scala:139:
diverging implicit expansion for type ((String, com.twitter.scalding.RichDate)) =>
Comparable[(String, com.twitter.scalding.RichDate)]
[error] starting with method $conforms in object Predef
[error]       implicitly[Ordering[(String, RichDate)]]
[error]                 ^
[error] one error found
[error] (scalding-date/test:compileIncremental) Compilation failed
[error] Total time: 5 s, completed Feb 10, 2016 2:27:14 PM